### ISSUE TITLE
Notion API Connection for form entries

### ISSUE THREAD

**Issue by thelifeandtimes** [deathtothecorporation/vaporware.network#11]
We are using Notion as our CRM, and for purposes of collecting contact records from the Website we will utilize their API. I have set up the Integration permissions to the "vaporware.network activity updates form entries" database with the "Activity Updates Form" internal integration.
<img width="328" alt="image" src="https://github.com/deathtothecorporation/vaporware.network/assets/82244264/3b9619c5-cf4d-435e-a306-1d029cd9655b">

Using the Notion API we want to take any form entries from `vaporware.network` and create a new database entry in the `CRM - Contact Records` database. Dependent on the entry's legibility, we want to do the following: 
- If the entry is a valid email, create a record with a "Form Entry Content" property of `<entry-text>`, set "Type" property to `Email` and "Email" property of `<entry-text>`.
- If the entry is a valid `@p`, create a record with a "Form Entry Content" property of `<entry-text>`, set "Type" property to `@p`, and "@p" property of `<entry-text>`.
- If the entry is not a valid email or `@p`, we want to return an error to the visitor suggesting they double check their entry

## Resources for implementation
Integration documentation: https://developers.notion.com/docs/create-a-notion-integration
Sample Repo: https://github.com/makenotion/notion-sdk-js/tree/main/examples/web-form-with-express
Create a new Database page documentation: https://developers.notion.com/reference/post-page

**Comment by themeix** [comment]
I never worked with notion but i can try

**Comment by thelifeandtimes** [comment]
Understood. Based on my research it should be fairly straightforward, but let me know if our current tech stack has limitations for supporting this for form entry and data capture.

@vcavallo ccing you here re: validating `@p`s on form entry. it may be that we just want to accept any string starting with `~abc`. depending on what validation tools we have at our disposal?

**Comment by vcavallo** [comment]
The “urbit-ob” npm package (https://www.npmjs.com/package/urbit-ob)
provides the following method to check if a string is a valid @p:

ob.isValidPatp(someString)

**Comment by thelifeandtimes** [comment]
@themeix can you provide an update here as well?

**Comment by themeix** [comment]
https://noteforms.com/

That would be a easy soluton

**Comment by thelifeandtimes** [comment]
continuing to use Google Sheets implementation for the time being.
