### ISSUE TITLE
Section Dividers

### ISSUE THREAD

**Issue by thelifeandtimes** [deathtothecorporation/vaporware.network#5]
- [x] Currently, the section dividers are diplaying as images. This means that when they change size responsively, they become taller. They should be rendered as vectorized lines instead of images
![image](https://github.com/deathtothecorporation/vaporware.network/assets/82244264/080c45f1-674c-46ba-9425-cf4dae683485)
- [x] Additionally, they are missing on the Experiments Index page
![image](https://github.com/deathtothecorporation/vaporware.network/assets/82244264/89ac0751-1bd4-4b82-ac91-2a0da5bcdb40)

**Comment by themeix** [comment]
Sorry, divider added

**Comment by themeix** [comment]
Its now in css
