### ISSUE TITLE
Missive Index

### ISSUE THREAD

**Issue by thelifeandtimes** [deathtothecorporation/vaporware.network#6]
![image](https://github.com/deathtothecorporation/vaporware.network/assets/82244264/b4f76d13-6ae3-415b-bc71-996fadbae78c)

- [x] Missive Card frame should include a white border around the image as well, as indicated in the figma:
![image](https://github.com/deathtothecorporation/vaporware.network/assets/82244264/53000156-fe03-4001-b941-e0c6adb56499)
- [x] metadata should not be stacked

- [x] min width for desktop display of missive cards should be 480px (with a max of 800), which means that at some breakpoint from ~1096 to 800 there should only be 1 column of posts.
![image](https://github.com/deathtothecorporation/vaporware.network/assets/82244264/c0228bf0-76dd-4430-b410-f6abca2f5c29)
- the load posts button works exactly as expected, thank you.

- [x] Breaking to mobile layout should occur at 800 pixels, and accordingly adjust the type of card that is served: 
![image](https://github.com/deathtothecorporation/vaporware.network/assets/82244264/b81f9e1b-1417-4f62-864c-f314ef4745de)

**Comment by themeix** [comment]
Fixed.. Will update the repo soon
