### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by thelifeandtimes** [deathtothecorporation/vaporware.network#7]
For the Homepage, Missive Index, and Experiments Index, the background image should be full bleed and 'centered' in the viewport. Sorry for not depicting this particularly well in the Figma, but here is a good example of what I am envisioning:
https://www.holium.com/

- the center of the image is always in the center of the viewport
- image height is equivalent to the viewport if viewport height > viewport width
- image width is equivalent to the viewport if viewport width > viewport height
- objects (cards, body copy, etc) should scroll over this image

**Comment by themeix** [comment]
Working on it
