### ISSUE TITLE
Experiments Template Card

### ISSUE THREAD

**Issue by thelifeandtimes** [deathtothecorporation/vaporware.network#9]
the big button link out should be to a url (it currently is a mailto:).
<img width="555" alt="image" src="https://github.com/deathtothecorporation/vaporware.network/assets/82244264/a1d8ae47-20c3-457c-af7b-c59fb443ed89">

If this is set in the markdown file for the page, that is acceptable and we can input accordingly.

**Comment by thelifeandtimes** [comment]
<img width="689" alt="image" src="https://github.com/deathtothecorporation/vaporware.network/assets/82244264/aacf4089-ee2a-4bce-ad03-4e5cf861d791">

At the mobile breakpoint, the header card should also flip to have the image stacked over the content:
<img width="654" alt="image" src="https://github.com/deathtothecorporation/vaporware.network/assets/82244264/091e07f4-df77-48d6-a245-076b61b984ac">

**Comment by themeix** [comment]
Working on it now
